# Generated by Django 2.0.4 on 2018-04-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('user_long', models.FloatField(max_length=50)),
                ('user_lat', models.FloatField(max_length=50)),
                ('user_status', models.CharField(max_length=20)),
            ],
        ),
    ]
